feat: add release-1.4.x config

diff --git a/.github/workflows/release-pr.yml b/.github/workflows/release-pr.yml
--- a/.github/workflows/release-pr.yml
+++ b/.github/workflows/release-pr.yml
@@ -523,7 +523,7 @@ jobs:
         fi
         
         jq -e '.[${{ steps.extract_branch.outputs.branch }}]' release.json ||
-          echo 'Invalid release branch: ${{ steps.extract_branch.outputs.branch }}. Make sure release.json includes an entry for this branch' && exit 1
+          echo 'Invalid release branch: ${{ steps.extract_branch.outputs.branch }}. Make sure release.json includes an entry for ${{ steps.extract_branch.outputs.branch }}.' && exit 1
       shell: "bash"
 name: "create release PR"
 "on":
