fix: bash logic

diff --git a/.github/workflows/release-pr.yml b/.github/workflows/release-pr.yml
--- a/.github/workflows/release-pr.yml
+++ b/.github/workflows/release-pr.yml
@@ -522,8 +522,10 @@ jobs:
           cd release
         fi
         
-        jq -e '.["${{ steps.extract_branch.outputs.branch }}"]' release.json ||
-          echo 'Invalid release branch: ${{ steps.extract_branch.outputs.branch }}. Make sure release.json includes an entry for ${{ steps.extract_branch.outputs.branch }}.' && exit 1
+        jq -e '.["${{ steps.extract_branch.outputs.branch }}"]' release.json && exit 0
+        
+        echo 'Invalid release branch: ${{ steps.extract_branch.outputs.branch }}. Make sure release.json includes an entry for ${{ steps.extract_branch.outputs.branch }}.'
+        exit 1
       shell: "bash"
 name: "create release PR"
 "on":
